spring:
  datasource:
    username: penta
    password: stagiu
    url: "jdbc:postgresql://localhost:5432/pentastagiu2021java"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


    show-sql: true
    properties:
      hibernate:
        format_sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG

 #       type:
 #        descriptor:
 #           sql:
  #            BasicBinder: TRACE


server:
  port: 8081